services:
  tfserving:
    build:
      context: .
      dockerfile: Dockerfile   # pastikan nama file sesuai
    container_name: tfserving
    ports:
      - "8501:8501"
      - "8500:8500"
    env_file:
      - .env   # <-- pakai ini untuk runtime env
    restart: unless-stopped

  prometheus:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
