global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "tfserving"
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ["tfserving:8501"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
